openapi: 3.0.0
info:
  title: Founda platform API
  version: 1.0.0
servers:
  - url: https://identity-oauth.eu.founda.com
  - url: https://api.eu.founda.com/1/health
paths:
  /oauth2/token:
    servers:
      - url: https://identity-oauth.eu.founda.com
    post:
      summary: Get an access token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - client_id
                - client_secret
                - grant_type
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                grant_type:
                  type: string
                  default: client_credentials
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                access_token: ory_at_V6G-ECLU6klFXBsfZhCc02wsdYqi2pSYUww65FS_sIY.XBVEe_1bJ10_3c26seZKtWNWU5FFMGeVErX58QY7wGM
                expires_in: 3599
                scope: ''
                token_type: bearer
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
                  scope:
                    type: string
  /organizations/:organizationId/fhir/4/Patient:
    servers:
      - url: https://api.eu.founda.com/1/health
    get:
      summary: Search patient by demographics
      parameters: 
      - schema:
        $ref: "#/components/parameters/authorization"
      - schema:
        $ref: "#/components/parameters/organizationId"
      - schema:
        $ref: "#/components/parameters/_id"
      - schema:
        $ref: "#/components/parameters/active"
      - schema:
        $ref: "#/components/parameters/family"
      - schema:
        $ref: "#/components/parameters/given"
      - schema:
        $ref: "#/components/parameters/identifier"
      - schema:
        $ref: "#/components/parameters/telecom"
      - schema:
        $ref: "#/components/parameters/birthdate"
      - schema:
        $ref: "#/components/parameters/address"
      - schema:
        $ref: "#/components/parameters/address-city"
      - schema:
        $ref: "#/components/parameters/address-country"
      - schema:
        $ref: "#/components/parameters/address-postalcode"
      - schema:
        $ref: "#/components/parameters/address-state"
      responses:
        '200':
          description: 'ok'
          content:
            application/json:
              example:
                resourceType: Bundle
                id: eae206f2-1b2d-4b9b-acea-6727cab3e351
                meta:
                  lastUpdated: '2023-10-05T14:34:11.283+00:00'
                type: searchset
                total: 1
                link:
                - relation: self
                  url: https://api.eu.founda.com/1/health/organizations/org-4c5739ba994d4ce9b5255d3f84a2d367/fhir/4/Patient?given=Duck&family=Donald&birthdate=1924-06-09&_profile=https://profiles.ihe.net/ITI/PDQm/
                entry:
                - fullUrl: https://api.eu.founda.com/1/health/organizations/org-4c5739ba994d4ce9b5255d3f84a2d367/fhir/4/Patient/2078
                  resource:
                    resourceType: Patient
                    id: '2078'
                    meta:
                      versionId: '1'
                      lastUpdated: '2023-10-05T14:29:14.124+00:00'
                      source: "#o1vJX8Q904hvVeMp"
                      tag:
                      - system: http://terminology.hl7.org/CodeSystem/v3-ActReason
                        code: HTEST
                        display: test health data
                    text:
                      status: generated
                      div: "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      \n      <p>Patient
                        Donald DUCK @ Acme Healthcare, Inc. MR = 654321</p>\n    \n    </div>"
                    identifier:
                    - use: usual
                      type:
                        coding:
                        - system: http://terminology.hl7.org/CodeSystem/v2-0203
                          code: MR
                      system: urn:oid:0.1.2.3.4.5.6.7
                      value: '654321'
                    active: true
                    name:
                    - use: official
                      family: Donald
                      given:
                      - Duck
                    gender: male
                    birthDate: '1924-06-09'
                    photo:
                    - contentType: image/gif
                      data: R0lGODlhEwARAPcAAAAAAAAA/+9aAO+1AP/WAP/eAP/eCP/eEP/eGP/nAP/nCP/nEP/nIf/nKf/nUv/nWv/vAP/vCP/vEP/vGP/vIf/vKf/vMf/vOf/vWv/vY//va//vjP/3c//3lP/3nP//tf//vf///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////yH5BAEAAAEALAAAAAATABEAAAi+AAMIDDCgYMGBCBMSvMCQ4QCFCQcwDBGCA4cLDyEGECDxAoAQHjxwyKhQAMeGIUOSJJjRpIAGDS5wCDly4AALFlYOgHlBwwOSNydM0AmzwYGjBi8IHWoTgQYORg8QIGDAwAKhESI8HIDgwQaRDI1WXXAhK9MBBzZ8/XDxQoUFZC9IiCBh6wEHGz6IbNuwQoSpWxEgyLCXL8O/gAnylNlW6AUEBRIL7Og3KwQIiCXb9HsZQoIEUzUjNEiaNMKAAAA7
                    contact:
                    - relationship:
                      - coding:
                        - system: http://terminology.hl7.org/CodeSystem/v2-0131
                          code: E
                      organization:
                        reference: Organization/2072
                        display: Walt Disney Corporation
                    managingOrganization:
                      reference: Organization/2072
                      display: ACME Healthcare, Inc
                  search:
                    mode: match


  /organizations/:organizationId/fhir/4/Patient/:patientId:
    get:
      summary: Get a patient by ID
      parameters:
      - schema:
        $ref: "#/components/parameters/authorization"
      - schema:
        $ref: "#/components/parameters/organizationId"
      - schema:
        $ref: "#/components/parameters/patientId"
      - schema:
        $ref: "#/components/parameters/_profile"
      responses:
        '200':
          description: 'ok'
          content:
            application/json:
              example:
                resourceType: Patient
                id: '2078'
                meta:
                  versionId: '1'
                  lastUpdated: '2023-10-05T14:29:14.124+00:00'
                  source: "#o1vJX8Q904hvVeMp"
                  tag:
                  - system: http://terminology.hl7.org/CodeSystem/v3-ActReason
                    code: HTEST
                    display: test health data
                text:
                  status: generated
                  div: "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      \n      <p>Patient Donald
                    DUCK @ Acme Healthcare, Inc. MR = 654321</p>\n    \n    </div>"
                identifier:
                - use: usual
                  type:
                    coding:
                    - system: http://terminology.hl7.org/CodeSystem/v2-0203
                      code: MR
                  system: urn:oid:0.1.2.3.4.5.6.7
                  value: '654321'
                active: true
                name:
                - use: official
                  family: Donald
                  given:
                  - Duck
                gender: male
                birthDate: '1924-06-09'
                photo:
                - contentType: image/gif
                  data: R0lGODlhEwARAPcAAAAAAAAA/+9aAO+1AP/WAP/eAP/eCP/eEP/eGP/nAP/nCP/nEP/nIf/nKf/nUv/nWv/vAP/vCP/vEP/vGP/vIf/vKf/vMf/vOf/vWv/vY//va//vjP/3c//3lP/3nP//tf//vf///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////yH5BAEAAAEALAAAAAATABEAAAi+AAMIDDCgYMGBCBMSvMCQ4QCFCQcwDBGCA4cLDyEGECDxAoAQHjxwyKhQAMeGIUOSJJjRpIAGDS5wCDly4AALFlYOgHlBwwOSNydM0AmzwYGjBi8IHWoTgQYORg8QIGDAwAKhESI8HIDgwQaRDI1WXXAhK9MBBzZ8/XDxQoUFZC9IiCBh6wEHGz6IbNuwQoSpWxEgyLCXL8O/gAnylNlW6AUEBRIL7Og3KwQIiCXb9HsZQoIEUzUjNEiaNMKAAAA7
                contact:
                - relationship:
                  - coding:
                    - system: http://terminology.hl7.org/CodeSystem/v2-0131
                      code: E
                  organization:
                    reference: Organization/2072
                    display: Walt Disney Corporation
                managingOrganization:
                  reference: Organization/2072
                  display: ACME Healthcare, Inc



components:
  parameters:
    authorization:
      name: Authorization
      in: header
      required: true
      description: The authorization header
      schema:
        type: string
    content-Type:
      name: content-type
      in: header
      required: true
      description: The content-type header
      schema:
        type: string
    organizationId:
      name: organizationId
      in: path
      required: true
      description: The organization ID
      schema:
        type: string
    patientId:
      name: patientId
      in: path
      required: true
      description: The patient ID
      schema:
        type: string
    _id:
      name: _id
      in: query
      required: false
      description: Resource (logical) identifier for the patient
      schema: 
        type: string
    active:
      name: active
      in: query
      required: false
      description: Search for active (true) or inactive (false) patients
      schema: 
        type: boolean
    family:
      name: family
      in: query
      required: false
      description: Family name or last name of the patient
      schema: 
        type: string
    given:
      name: given
      in: query
      required: false
      description: Given name of the patient
      schema: 
        type: string
    identifier:
      name: identifier
      in: query
      required: false
      description: A patient identifier, formatted as system|value. Multiple identifiers can be added.
      schema: 
        type: string
    telecom:
      name: telecom
      in: query
      required: false
      description: Telecommunication details
      schema: 
        type: string
    birthdate:
      name: birthdate
      in: query
      required: false
      description: Patient's birthday, e.g. "2000-10-01"
      schema: 
        type: string
    address:
      name: address
      in: query
      required: false
      description: A known address for the patient
      schema: 
        type: string
    address-city:
      name: address-city
      in: query
      required: false
      description: The city the patient lives in
      schema: 
        type: string
    address-country:
      name: address-country
      in: query
      required: false
      description: The country the patient lives in
      schema: 
        type: string
    address-postalcode:
      name: address-postalcode
      in: query
      required: false
      description: The postal code of the patient's address
      schema: 
        type: string
    address-state:
      name: address-state
      in: query
      required: false
      description: The state the patient lives in
      schema: 
        type: string
    gender:
      name: gender
      in: query
      required: false
      description: The patient's gender
      schema: 
        type: string
    mothersMaidenName:
      name: mothersMaidenName
      in: query
      required: false
      description: The patient's mother's maiden name
      schema: 
        type: string
    _profile:
      name: _profile
      in: query
      required: true
      description: The profile transaction URL that the request is for
      schema: 
        type: string
        default: https://profiles.ihe.net/ITI/PDQm
